#
# Module manifest for module 'UnisphereExporter'
#
# Generated by: Clint Colding
#
# Generated on: 3/5/2019
#

@{

    # Version number of this module.
    ModuleVersion = '0.1.0'

    # ID used to uniquely identify this module
    GUID = '3a933558-9aef-45ca-9f46-fa8c4b010bba'

    # Author of this module
    Author = 'Clint Colding'

    # Description of the functionality provided by this module
    Description = 'PowerShell module for exporting VMAX metrics to Prometheus...'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
        "UnisphereExporter.psm1"
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = "*"

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

}